from typing import Protocol, List, Optional
from app.domain.models import InspectionCreate, InspectionResponse, InspectionStatus

class DatabasePort(Protocol):
    async def create_inspection(self, data: InspectionCreate, org_id: str) -> InspectionResponse: ...
    async def get_inspection(self, inspection_id: str, org_id: Optional[str] = None) -> Optional[InspectionResponse]: ...
    async def list_inspections(self, org_id: Optional[str] = None, limit: int = 50, offset: int = 0) -> List[InspectionResponse]: ...
    async def update_inspection_status(self, inspection_id: str, status: InspectionStatus, summary: Optional[str] = None, org_id: Optional[str] = None) -> InspectionResponse: ...