from typing import Protocol, Dict, Any

class VoicePort(Protocol):
    async def generate_connection_token(self, room_name: str, participant_identity: str) -> str: ...
    async def dispatch_agent(self, room_name: str, metadata: Dict[str, Any]) -> bool: ...